PlayerId:
  name: id
  in: path
  required: true
  description: Unique player identifier (UUID)
  schema:
    type: string
    format: uuid
    example: 550e8400-e29b-41d4-a716-446655440000

MatchId:
  name: id
  in: path
  required: true
  description: Unique match identifier (UUID)
  schema:
    type: string
    format: uuid
    example: 770e8400-e29b-41d4-a716-446655440000

Page:
  name: page
  in: query
  required: false
  description: Page number for pagination
  schema:
    type: integer
    minimum: 1
    default: 1
    example: 1

Limit:
  name: limit
  in: query
  required: false
  description: Number of items per page
  schema:
    type: integer
    minimum: 1
    maximum: 100
    default: 20
    example: 20

CountryCode:
  name: country
  in: path
  required: true
  description: ISO 3166-1 alpha-2 country code
  schema:
    type: string
    pattern: '^[A-Z]{2}$'
    example: US

TimeRange:
  name: timeRange
  in: query
  required: false
  description: Time range filter for leaderboard data
  schema:
    type: string
    enum: [24h, 7d, 30d, all]
    default: all
    example: 7d
